src/com/fly/entity/Picrecommend.java

package com.fly.entity;

import java.util.List;

import com.jfinal.plugin.activerecord.Model;

public class Picrecommend extends Model<Picrecommend>
{
    /**
     * 
     */
    private static final long serialVersionUID = 9160601585945143893L;

    public static final Picrecommend me = new Picrecommend();

    public List<Picrecommend> listAll()
    {
        return find("select * from picrecommend order by sn");
    }

    public List<Picrecommend> listIndex()
    {
        return find(
                "select * from picrecommend where deleted=0 order by sn,id");
    }

}

src/com/fly/entity/Userrole.java

package com.fly.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.Page;

public class Userrole extends Model<Userrole>
{
    /**
     * 
     */
    private static final long serialVersionUID = -3724933206673873541L;

    public static final Userrole me = new Userrole();

    public User getUser()
    {
        return User.me.findById(getInt("user_id"));
    }

    public Role getRole()
    {
        return Role.me.findById(getInt("role_id"));
    }

    public Userrole findByUserId(int user_id)
    {
        return me.findFirst("select * from userrole  where user_id=?", user_id);
    }

    public Page<Userrole> findByRoleId(int pageNumber, int pageSize,
            int role_id)
    {
        return paginate(pageNumber, pageSize, "select *",
                "from userrole where role_id=?", role_id);
    }

}

WebRoot/WEB-INF/content/admins/adviceDetail.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<!-- 引入基本库和js，css文件 --> 
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>${siteName}后台管理</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="icon" href="${base}/favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="${base}/kindeditor-4.1.10/plugins/code/prettify.css" />
	<script charset="utf-8" src="${base}/kindeditor-4.1.10/kindeditor.js"></script>
	<script charset="utf-8" src="${base}/kindeditor-4.1.10/lang/zh_CN.js"></script>
	<script charset="utf-8" src="${base}/kindeditor-4.1.10/plugins/code/prettify.js"></script>
   <%@ include file="/WEB-INF/content/admins/taglib.jsp"%> 
</head>
<body>
<%@ include file="/WEB-INF/content/admins/header.jsp"%> 



<div class="am-cf admin-main">
<%@ include file="/WEB-INF/content/admins/side.jsp"%> 

  <!-- content start -->
  <div class="admin-content" id="admin-content">
  
  	<ol class="am-breadcrumb">
	  <li><a href="${base}/admins/" class="am-icon-home">后台首页</a></li>
	  <li><a href="${base}/admins/adviceList/">意见和建议列表</a></li>
	  <li>意见和建议详情</li>
	</ol>
	
    <div class="am-g">
      <div class="am-u-sm-12">
          <table class="am-table">
          	<tr>
          		<td width="150px">意见和建议</td>
          		<td>
          			${advice.content}
          		</td>
          	</tr>
          	<tr>
          		<td>关联用户</td>
          		<td>
          			${advice.username}
          		</td>
          	</tr>
          	<tr>
          		<td>姓名</td>
          		<td>
          			${advice.name}
          		</td>
          	</tr>
          	<tr>
          		<td>联系方式</td>
          		<td>
          			${advice.contact}
          		</td>
          	</tr>
          	<tr>
          		<td>创建时间</td>
          		<td>
          			<fmt:formatDate value="${advice.create_time}" pattern="yyyy-MM-dd HH:mm:ss"/>
          		</td>
          	</tr>
          	<tr>
          		<td><a type="button" class="am-btn am-btn-default" onclick="javascript:history.back(-2)">返回</a></td>
          		<td></td>
          	</tr>
          </table>
      </div>
    </div>
    
    
  </div>
  <!-- content end -->

</div>

<script>
	prettyPrint();
</script>
<%@ include file="/WEB-INF/content/admins/footer.jsp"%> 
</body>
</html>

WebRoot/WEB-INF/content/admins/adviceList.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<!-- 引入基本库和js，css文件 --> 
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>${siteName}后台管理</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="icon" href="${base}/favicon.ico" type="image/x-icon" />
   <%@ include file="/WEB-INF/content/admins/taglib.jsp"%> 
</head>
<body>
<%@ include file="/WEB-INF/content/admins/header.jsp"%> 



<div class="am-cf admin-main">
<%@ include file="/WEB-INF/content/admins/side.jsp"%> 

  <!-- content start -->
  <div class="admin-content" id="admin-content">
  
  	<ol class="am-breadcrumb">
	  <li><a href="${base}/admins/" class="am-icon-home">后台首页</a></li>
	  <li>意见和建议</li>
	</ol>
	
    <div class="am-g">
      <div class="am-u-sm-12">
          <table class="am-table am-table-striped am-table-hover table-main am-table-bordered">
            <thead>
              <tr>
                <th class="table-id">ID</th>
                <th class="table-title">关联用户</th>
                <th class="table-type">内容</th>
                <th class="table-author">姓名</th>
                <th class="table-date">联系方式</th>
                <th class="table-date">创建时间</th>
                <th class="table-set" width="230px">操作</th>
              </tr>
          </thead>
          <tbody>
          	<c:forEach items="${advicePage.list}" var="g">
	            <tr>
	              <td>${g.id}</td>
	              <td>${g.username }</td>
	              <td>${g.content_show}</td>
	              <td>${g.name}</td>
	              <td>${g.contact}</td>
	              <td><fmt:formatDate value="${g.create_time}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
	              <td>
	                <div class="am-btn-toolbar">
	                  <div class="am-btn-group am-btn-group-xs">
	                    <a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="${base}/admins/adviceDetail?id=${g.id}"><span class="am-icon-pencil-square-o"></span>详情</a>
	                    <a class="am-btn am-btn-default am-btn-xs am-text-danger" href="${base}/admins/adviceDelete?id=${g.id}" onclick="return confirm('您确定要删除该意见和建议吗？');"><span class="am-icon-trash-o"></span> 删除</a>
	                    <c:if test="${g.isread==0}">
	                    	<a class="am-btn am-btn-default am-btn-xs am-text-success" href="${base}/admins/adviceRead?id=${g.id}"> 标记为已读</a>
	                    </c:if>
	                    <c:if test="${g.isread==1}">
	                    	<a class="am-btn am-btn-default am-btn-xs am-text-success am-disabled">已读</a>
	                    </c:if>
	                  </div>
	                </div>
	              </td>
	            </tr>
          	</c:forEach>
          </tbody>
        </table>
        <c:set var="currentPage" value="${advicePage.pageNumber}" />
				<c:set var="totalPage" value="${advicePage.totalPage}" />
				<c:set var="actionUrl" value="${base}/admins/adviceList?page=" />
				<c:set var="urlParas" value=""/>
				<center>
					<%@ include file="/common/_paginate.jsp"%>
				</center>
      </div>
    </div>
    
    
  </div>
  <!-- content end -->

</div>


<%@ include file="/WEB-INF/content/admins/footer.jsp"%> 
</body>
</html>

WebRoot/WEB-INF/content/admins/footer.jsp
<footer>
  <hr>
  <p class="am-padding-left">&copy; 2016 ${siteName }</p>
</footer>

WebRoot/WEB-INF/content/admins/gonggaoAdd.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<!-- 引入基本库和js，css文件 --> 
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>${siteName}后台管理</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="icon" href="${base}/favicon.ico" type="image/x-icon" />
   <%@ include file="/WEB-INF/content/admins/taglib.jsp"%> 
</head>
<body>
<%@ include file="/WEB-INF/content/admins/header.jsp"%> 



<div class="am-cf admin-main">
<%@ include file="/WEB-INF/content/admins/side.jsp"%> 

  <!-- content start -->
  <div class="admin-content" id="admin-content">
  	<ol class="am-breadcrumb">
	  <li><a href="${base}/admins/" class="am-icon-home">后台首页</a></li>
	  <li><a href="${base}/admins/gonggaoList/">滚动公告列表</a></li>
	  <li>新建滚动公告</li>
	</ol>
	
    <div class="am-g">
      <div class="am-u-sm-12">
     	<form class="am-form am-form-horizontal" action="${base}/admins/gonggaoSave/" method="post" enctype="multipart/form-data">
		  <div class="am-form-group">
		    <label for="gonggao-add-content" class="am-u-sm-2 am-form-label">内容</label>
		    <div class="am-u-sm-10">
		      <input type="text" id="gonggao-add-content" name="gonggao.content"  placeholder="请输入公告内容,支持标签和style来设置自定义样式，具体结合效果自己测试">
		    </div>
		  </div>
		  
		  <div class="am-form-group">
		    <label for="gonggao-add-url" class="am-u-sm-2 am-form-label">URL</label>
		    <div class="am-u-sm-10">
		      <input type="text" id="gonggao-add-url" name="gonggao.url" placeholder="请输入公告URL，没有连接请输入‘#’">
		    </div>
		  </div>
		  
		  <div class="am-form-group">
		    <label for="gonggao-add-sn" class="am-u-sm-2 am-form-label">排序号</label>
		    <div class="am-u-sm-10">
		      <input type="number" id="gonggao-add-sn" name="gonggao.sn" placeholder="不填写自动生成，排序号按从小到大自动播放">
		    </div>
		  </div>
		
		  <div class="am-form-group">
		    <div class="am-u-sm-10 am-u-sm-offset-2">
		      <button type="submit" class="am-btn am-btn-default">提交</button>
		      <a type="button" class="am-btn am-btn-default" onclick="javascript:history.back(-2)">返回</a>
		    </div>
		  </div>
		</form>
      </div>
    </div>
  </div>
  <!-- content end -->

</div>

<%@ include file="/WEB-INF/content/admins/footer.jsp"%> 

</body>
</html>

WebRoot/WEB-INF/content/admins/gonggaoList.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<!-- 引入基本库和js，css文件 --> 
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>${siteName}后台管理</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="icon" href="${base}/favicon.ico" type="image/x-icon" />
   <%@ include file="/WEB-INF/content/admins/taglib.jsp"%> 
</head>
<body>
<%@ include file="/WEB-INF/content/admins/header.jsp"%> 



<div class="am-cf admin-main">
<%@ include file="/WEB-INF/content/admins/side.jsp"%> 

  <!-- content start -->
  <div class="admin-content" id="admin-content">
  
  	<ol class="am-breadcrumb">
	  <li><a href="${base}/admins/" class="am-icon-home">后台首页</a></li>
	  <li>滚动公告列表</li>
	</ol>
	
    <div class="am-g">
      <div class="am-u-sm-12">
          <table class="am-table am-table-striped am-table-hover table-main am-table-bordered">
            <thead>
              <tr>
                <th class="table-id">ID</th>
                <th class="table-title">内容</th>
                <th class="table-type">链接</th>
                <th class="table-author">排序号</th>
                <th class="table-date">修改日期</th>
                <th class="table-set">操作</th>
              </tr>
          </thead>
          <tbody>
          	<c:forEach items="${gonggaoList}" var="g">
	            <tr>
	              <td>${g.id}</td>
	              <td>${g.content }</td>
	              <td>${g.url}</td>
	              <td>${g.sn }</td>
	              <td><fmt:formatDate value="${g.create_time}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
	              <td>
	                <div class="am-btn-toolbar">
	                  <div class="am-btn-group am-btn-group-xs">
	                    <a class="am-btn am-btn-default am-btn-xs am-text-secondary" href="${base}/admins/gonggaoEdit?id=${g.id}"><span class="am-icon-pencil-square-o"></span> 编辑</a>
	                    <a class="am-btn am-btn-default am-btn-xs am-text-danger" href="${base}/admins/gonggaoDelete?id=${g.id}" onclick="return confirm('您确定要删除该公告吗？');"></span> 删除</a>
	                  </div>
	                </div>
	              </td>
	            </tr>
          	</c:forEach>
          </tbody>
        </table>
        <div class="am-btn-group am-btn-group-xs">
          <button type="button" class="am-btn am-btn-default" onclick="javascript:location.href='${base}/admins/gonggaoAdd/'"><span class="am-icon-plus"></span> 新增</button>
          <button type="button" class="am-btn am-btn-default" onclick="javascript:location.href='${base}/admins/refreshGonggao/'"><i class="am-icon-circle-o-notch am-icon-spin"></i> 刷新缓存</button>
        </div>
        <div class="am-cf">
			  共 ${fn:length(gonggaoList)} 条记录
		</div>
      </div>
    </div>
    
    
  </div>
  <!-- content end -->

</div>


<%@ include file="/WEB-INF/content/admins/footer.jsp"%> 
</body>
</html>

WebRoot/WEB-INF/content/admins/header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    <style type="text/css">
    	.am-topbar, .am-topbar a {
		    color: black;
		}
    </style>
<header class="am-topbar admin-header" style="background:#09C;">
  <div class="am-topbar-brand">
  	<%-- <img alt="" src="${base}/images/lovepandaadmin.png" style="height: 50px"> --%>
  	<p class="am-kai" style="color: white;">${siteName}后台管理</p>
  </div>

  <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only" data-am-collapse="{target: '#topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span class="am-icon-bars"></span></button>

  <div class="am-collapse am-topbar-collapse" id="topbar-collapse">

    <ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list">
      <li>
        <a><span class="am-icon-users"></span> ${sessionScope.loginUser.username}</a>
      </li>
      <li><a href="${base}/"><span class="am-icon-power-off"></span> 退出后台</a></li>
    </ul>
  </div>
</header>

WebRoot/WEB-INF/content/admins/linkAdd.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<!-- 引入基本库和js，css文件 --> 
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>${siteName}后台管理</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="icon" href="${base}/favicon.ico" type="image/x-icon" />
   <%@ include file="/WEB-INF/content/admins/taglib.jsp"%>
   <script language="javascript" type="text/javascript" src="${base}/sucai/My97DatePicker/WdatePicker.js"></script>
   <style type="text/css">
   	.layui-layer-content{
   		margin: 10px;
   	}
   </style> 
   <script type="text/javascript">
   </script> 
</head>
<body>
<%@ include file="/WEB-INF/content/admins/header.jsp"%> 



<div class="am-cf admin-main">
<%@ include file="/WEB-INF/content/admins/side.jsp"%> 

  <!-- content start -->
  <div class="admin-content" id="admin-content">
  
  	<ol class="am-breadcrumb">
	  <li><a href="${base}/admins/" class="am-icon-home">后台首页</a></li>
	  <li>新建友情链接</li>
	</ol>
	
	
    <div class="am-g">
      <div class="am-u-sm-12">
		<form class="am-form" action="${base}/admins/linkSave/" method="post" enctype="multipart/form-data">
			  <fieldset>
			    <legend>新建友情链接</legend>
			    <div class="am-form-group">
			      <label for="admin-admin-picRec-form-title">网站名</label>
			      <input type="text" class="" id="admin-admin-picRec-form-title" name="link.title" placeholder="请输入网站名" required>
			    </div>
			    <div class="am-form-group">
			      <label for="admin-admin-picRec-form-url">URL</label>
			      <input type="url" id="doc-vld-url-2" placeholder="请输入网址"  name="link.url" required/>
			    </div>
			     <div class="am-form-group">
			      <label for="admin-admin-picRec-form-sn">排序</label>
			      <input type="number" id="admin-admin-picRec-form-sn" name="link.sn" placeholder="请输入排序号，不输入默认为其ID" />
			    </div>
			    <p><button type="submit" class="am-btn am-btn-default">提交</button></p>
			  </fieldset>
			</form>
 			
      </div>
    </div>
    
    
  </div>
  <!-- content end -->

</div>


<%@ include file="/WEB-INF/content/admins/footer.jsp"%> 
</body>
</html>

WebRoot/WEB-INF/content/admins/userList.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<head>
<!-- 引入基本库和js，css文件 --> 
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>${siteName}后台管理</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="icon" href="${base}/favicon.ico" type="image/x-icon" />
   <%@ include file="/WEB-INF/content/admins/taglib.jsp"%> 
</head>
<body>
<%@ include file="/WEB-INF/content/admins/header.jsp"%> 
<div class="am-cf am-g admin-main">
<%@ include file="/WEB-INF/content/admins/side.jsp"%> 

  <!-- content start -->
  <div class="admin-content" id="admin-content">
	  <ol class="am-breadcrumb">
		  <li><a href="${base}/admins/" class="am-icon-home">后台首页</a></li>
		  <li>用户列表</li>
	  </ol>
  	<script type="text/javascript">
 		 function editUserRole(id){
	  		$.post("${base}/admins/userRoleEdit?id="+id,
			   function(data){
			     $("#userroleeditform > input[name='id']").val(data.id);
			     $("#userroleselect").empty(); 
			     if(data.userrole==undefined){
			    	 $("#userroleselect").append("<option value='0'>无角色</option>");
				     $.each( data.roleList, function(index, content)
		    		 {  
				     	$("#userroleselect").append("<option value='"+content.id+"'>"+content.role_name+"</option>");
		    		 });
			     }else{
			    	 $("#userroleselect").append("<option value='0'>无角色</option>");
			    	 $.each( data.roleList, function(index, content)
		    		 {  
			    		 if(data.userrole.role_id==content.id){
					     	$("#userroleselect").append("<option value='"+content.id+"' selected='selected'>"+content.role_name+"</option>");
			    		 }else{
					     	$("#userroleselect").append("<option value='"+content.id+"'>"+content.role_name+"</option>");
			    		 }
		    		 });
			     }
	  			var index=layer.open({
				    type: 1,
				    skin: 'layui-layer-rim', //加上边框
				    area: ['420px', '240px'], //宽高
				    btn:['提交'],
				    yes:function(){
				    	$("#userroleeditform").submit();
				    },
				    content: $("#userroleeditform")
				});
				 layer.title(data.username+'：指定角色', index);
			   }, "json");
	  	}
 		 function deleteUser(id){
 			layer.confirm('确定封禁该用户吗？封禁后可以从封禁的用户列表中进行恢复。封禁的用户不能登录。', {
   			    btn: ['确定封禁','取消'] //按钮
   			}, function(){
		   		location.href="${base}/admins/userDelete?id="+id;
   			}, function(){
   			    layer.msg('取消了');
   			});
 		 }
	</script>
   	
	  <div class="am-g">
	  	<div class="am-u-sm-12">
			<form action="${base}/admins/userList/" method="get">
				<h3>用户条件检索</h3>
				<table class="am-table">
				  <tr>
				    <th>用户名</th>
				    <th>
				    	<input type="text" class="am-form-field am-radius" name="user.username" value="${user.username}" />
				    </th>
				    <th>昵称</th>
				    <th>
				    	<input type="text" class="am-form-field am-radius" name="user.realname" value="${user.realname}" />
				    </th>
				  </tr>
				  <tr>
				    <th>类型</th>
				    <th>
				    	<select name="user.type" value="${user.type}">
				    		<c:if test="${empty user.type}">
					    		<option value="" selected="selected">全部</option>
					    		<option value="0">注册用户</option>
					    		<option value="1">QQ互联用户</option>
				    		</c:if>
				    		<c:if test="${user.type==0}">
					    		<option value="">全部</option>
					    		<option value="0" selected="selected">注册用户</option>
					    		<option value="1">QQ互联用户</option>
				    		</c:if>
				    		<c:if test="${user.type==1}">
					    		<option value="">全部</option>
					    		<option value="0">注册用户</option>
					    		<option value="1" selected="selected">QQ互联用户</option>
				    		</c:if>
				    	</select>
				    </th>
				     <th colspan="2">
				  		<button type="submit" class="am-btn am-btn-primary">搜索</button>
				     </th>
				  </tr>
				</table>
			</form>
			<!-- 分割线 -->
			<hr data-am-widget="divider" style="" class="am-divider am-divider-dashed"/>
	  		<table class="am-table am-table-bordered am-table-striped am-table-hover">
			    <thead>
			        <tr>
			            <th width="20%">用户名</th>
			            <th width="20%">昵称</th>
			            <th width="15%">类型</th>
			            <th width="10%">角色</th>
			            <th width="15%">创建时间</th>
			            <th width="20%">操作</th>
			        </tr>
			    </thead>
			    <tbody>
				    <c:forEach items="${userPage.list}" var="l">
				        <tr class="">
				            <td>${l.username}</td>
				            <td>${l.realname}</td>
				            <td>
				            	<c:if test="${l.type==0}">
				            		注册用户
				            	</c:if>
				            	<c:if test="${l.type==1 }">
				            		QQ互联用户
				            	</c:if>
				            </td>
				            <td>${l.role}</td>
				            <td><fmt:formatDate value="${l.create_time}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
				            <td>
				            	<div class="am-btn-toolbar">
				                  <div class="am-btn-group am-btn-group-xs">
				                    <a class="am-btn am-btn-default am-btn-xs am-text-danger" onclick="deleteUser(${l.id})"><span class="am-icon-trash-o"></span> 封禁</a>
				                    <a class="am-btn am-btn-default am-btn-xs am-text-primary" onclick="editUserRole(${l.id})"><span class="am-icon-hand-o-right"></span> 指定角色</a>
				                  </div>
				                </div>
				            </td>
				        </tr>
				    </c:forEach>
			    </tbody>
			</table>
				<c:set var="currentPage" value="${userPage.pageNumber}" />
				<c:set var="totalPage" value="${userPage.totalPage}" />
				<c:set var="actionUrl" value="${base}/admins/userList?user.username=${user.username}&user.realname=${user.realname}&user.type=${user.type}&page=" />
				<c:set var="urlParas" value=""/>
				<center>
					<%@ include file="/common/_paginate.jsp"%>
				</center>
	    </div>
	 </div>
		
  </div>
  <!-- content end -->
</div>

<%@ include file="/WEB-INF/content/admins/footer.jsp"%> 
</body>
	<form id="userroleeditform" action="${base}/admins/userRoleSave/" style="padding: 20px;display: none;">
      <input type="hidden" name="id" value="">
	      <select id="userroleselect" name="roleId">
	      </select>
    </form>
</html>